### ISSUE TITLE
Broken Fog when the textures are installed

### ISSUE THREAD

**Issue by TommyVercetti345** [santiago046/ppsspp-mh2-texture-pack#1]
![Image](https://github.com/user-attachments/assets/4dbe5eeb-3e4d-42b4-9bc0-95258cf239e3)
![Image](https://github.com/user-attachments/assets/c80f2aec-cd92-4f6e-a35f-8da1606c5a66)

when i use the mod and i launch the game i get this problem where in a distance everything is so foggy and model look broken and transparency is broken i use ULUS10280

**Comment by santiago046** [comment]
Thanks for reporting it. Which PPSSPP version are you using? What platform are you playing (PC Windows, Linux, Android etc)?

**Comment by TommyVercetti345** [comment]
> Thanks for reporting it. Which PPSSPP version are you using? What platform are you playing (PC Windows, Linux, Android etc)?

i'm using the the very latest version of PPSSPP and i'm playing on windows

**Comment by TommyVercetti345** [comment]
what took you long to respond?

**Comment by TommyVercetti345** [comment]
dang :(

**Comment by santiago046** [comment]
I am still investigating what could be causing this issue. In the meantime, could you tweak your PPSSPP settings, like trying different Backend modes? Also, could you try older versions of the texture pack — see [Releases](https://github.com/santiago046/ppsspp-mh2-texture-pack/releases) and let me know if any of them works?

**Comment by TommyVercetti345** [comment]
> I am still investigating what could be causing this issue. In the meantime, could you tweak your PPSSPP settings, like trying different Backend modes? Also, could you try older versions of the texture pack — see [Releases](https://github.com/santiago046/ppsspp-mh2-texture-pack/releases) and let me know if any of them works?

okay thanks i already tested D3D9 and OpenGL and no options i touched worked so i'm gonna try the older version

**Comment by TommyVercetti345** [comment]
the game is still bugged in 2.0.1 version of the mod i guess your mod is lacking support for the latest version of ppsspp

**Comment by santiago046** [comment]
PPSSPP 1.18, Windows x64:

![Image](https://github.com/user-attachments/assets/246f6c99-d21d-4981-a1d1-19773de870e3)

Could you also try the first version, which uses ZIM instead of KTX2 texture format? If the bug goes away, I think it would be a problem with PPSSPP or your system.

**Comment by TommyVercetti345** [comment]
> PPSSPP 1.18, Windows x64: ![Image](https://github.com/user-attachments/assets/312cbed3-ccb9-426d-b099-01f31622ff77)
> 
> Could you also try the first version, which uses ZIM instead of KTX2 texture format? If the bug goes away, I think it would be a problem with PPSSPP or your system.

so i'll have to reset all my graphics settings then?

**Comment by TommyVercetti345** [comment]
i've resetted my graphics settings and everything and STILL nothing worked

**Comment by TommyVercetti345** [comment]
could you please send me your PPSSPP config?

**Comment by TommyVercetti345** [comment]
i used the first version that had zim (2.0.0) and i'm still having the same problem

**Comment by TommyVercetti345** [comment]
the first version works so can you please release a version that's with zim instead?

**Comment by santiago046** [comment]
Since I don't have a Windows system, I had to ask a friend to test it. It turned out he did not enable the **Replace textures** options in the settings, meaning the texture pack was not activated in the screenshot I sent. I have fixed it now, and as you can see, it's working fine.

----

> could you please send me your PPSSPP config?

Here's his PPSSPP Settings [INI(https://github.com/user-attachments/files/18630767/ppsspp.txt). If you plan to replace your settings with these ones, make sure to backup your ppsspp.ini first.

----

> the first version works so can you please release a version that's with zim instead?

Releases are based in the repo files. That means I have to switch to ZIM again to make it possible 🫤. I encourage you to open an issue in the [PPSSPP repository](https://github.com/hrydgard/ppsspp) as it appears to be a problem related to decoding Basisu KTX2 on your system.

**Comment by TommyVercetti345** [comment]
> Since I don't have a Windows system, I had to ask a friend to test it. It turned out he did not enable the **Replace textures** options in the settings, meaning the texture pack was not activated in the screenshot I sent. I have fixed it now, and as you can see, it's working fine.
> 
> > could you please send me your PPSSPP config?
> 
> Here's his PPSSPP Settings [INI(https://github.com/user-attachments/files/18630767/ppsspp.txt). If you plan to replace your settings with these ones, make sure to backup your ppsspp.ini first.
> 
> > the first version works so can you please release a version that's with zim instead?
> 
> Releases are based in the repo files. That means I have to switch to ZIM again to make it possible 🫤. I encourage you to open an issue in the [PPSSPP repository](https://github.com/hrydgard/ppsspp) as it appears to be a problem related to decoding Basisu KTX2 on your system.

dang

**Comment by TommyVercetti345** [comment]
i think it might be because i use the OpenGL backend

**Comment by TommyVercetti345** [comment]
i had the same problem when i got back to OpenGL so it's an issue with the OpenGL rendering i used the config with OpenGL instead and the issue still is there and when i use D3D11 my game crashes so it might be your mods issue with OpenGL

**Comment by santiago046** [comment]
Since this appears to be related to KTX2 texture handling in PPSSPP's OpenGL backend on Windows, I suggest you report this issue in the PPSSPP repository.

**Comment by TommyVercetti345** [comment]
> Since this appears to be related to KTX2 texture handling in PPSSPP's OpenGL backend on Windows, I suggest you report this issue in the PPSSPP repository.

Alright But i don't really think they like manhunt 2 but okay
